### ISSUE TITLE
"RuntimeError: CUDA out of memory." [BUG?]

### ISSUE THREAD

**Issue by Cyber-Snake** [ptrsuder/IEU.Winforms#29]
Started happening lately. I have "auto set tille dimensions" enabled which sets tile res to 893x893 and it always fails to upscale,sometimes lowering it help but most of the time I still get the same error. I have RTX 2080 8GB.

`[12.10.2020 14:30:26] Traceback (most recent call last):
[12.10.2020 14:30:26]   File "IEU_test.py", line 119, in <module>
[12.10.2020 14:30:26]     output = model(img_LR).data.squeeze(0).float().cpu().clamp_(0, 1).numpy()
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[12.10.2020 14:30:26]     result = self.forward(*input, **kwargs)
[12.10.2020 14:30:26]   File "C:\ESRGAN\architecture.py", line 37, in forward
[12.10.2020 14:30:26]     x = self.model(x)
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[12.10.2020 14:30:26]     result = self.forward(*input, **kwargs)
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\container.py", line 117, in forward
[12.10.2020 14:30:26]     input = module(input)
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
[12.10.2020 14:30:26]     result = self.forward(*input, **kwargs)
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 419, in forward
[12.10.2020 14:30:26]     return self._conv_forward(input, self.weight)
[12.10.2020 14:30:26]   File "C:\Users\User\AppData\Local\Programs\Python\Python38\lib\site-packages\torch\nn\modules\conv.py", line 415, in _conv_forward
[12.10.2020 14:30:26]     return F.conv2d(input, weight, self.bias, self.stride,
[12.10.2020 14:30:26] RuntimeError: CUDA out of memory. Tried to allocate 3.04 GiB (GPU 0; 8.00 GiB total capacity; 3.11 GiB already allocated; 2.77 GiB free; 3.13 GiB reserved in total by PyTorch)
[12.10.2020 14:30:26] Error ocured during ESRGAN work!`

**Comment by ptrsuder** [comment]
It just sets too big tiles dimensions, you can change it by not using "auto set tile dimensions" for now or by lowering "magick numbers" in Expose properties.

**Comment by XLRT** [comment]
On my 2070 Super 8GB setting to 512x512 solves this.
