### ISSUE TITLE
app does not start.

### ISSUE THREAD

**Issue by ActDeco** [ptrsuder/IEU.Winforms#40]
When I start ImageEnhancingUtility.Winforms.exe,they will show me an error window.
------
MyHandler caught: 未将对象引用设置到对象的实例。
------

Version: ImageEnhancingUtility.Winforms.0.13.0

**Comment by kongmao45678** [comment]
Same problem, in 0.13.0.
But using version 0.12 is normal.

**Comment by ptrsuder** [comment]
Go to Windows Event Viewer and find crash log

**Comment by Gabstom** [comment]
Same problem on 0.13.0

Log:
```
Application: ImageEnhancingUtility.Winforms.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.NullReferenceException
   at ImageEnhancingUtility.Winforms.MainForm.MainForm_Resize(System.Object, System.EventArgs)
   at System.Windows.Forms.Control.OnResize(System.EventArgs)
   at System.Windows.Forms.Form.OnResize(System.EventArgs)
   at System.Windows.Forms.Control.OnSizeChanged(System.EventArgs)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.UpdateBounds(Int32, Int32, Int32, Int32)
   at System.Windows.Forms.Control.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Form.SetBoundsCore(Int32, Int32, Int32, Int32, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.ScrollableControl.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Form.ScaleControl(System.Drawing.SizeF, System.Windows.Forms.BoundsSpecified)
   at System.Windows.Forms.Control.ScaleControl(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   at System.Windows.Forms.ContainerControl.Scale(System.Drawing.SizeF, System.Drawing.SizeF, System.Windows.Forms.Control)
   at System.Windows.Forms.ContainerControl.PerformAutoScale(Boolean, Boolean)
   at System.Windows.Forms.ContainerControl.PerformNeededAutoScaleOnLayout()
   at System.Windows.Forms.ContainerControl.OnLayoutResuming(Boolean)
   at System.Windows.Forms.Control.ResumeLayout(Boolean)
   at ImageEnhancingUtility.Winforms.MainForm.InitializeComponent()
   at ImageEnhancingUtility.Winforms.MainForm..ctor()
   at ImageEnhancingUtility.Winforms.Program.Main()

Event ID: 1026
```

```
Faulting application name: ImageEnhancingUtility.Winforms.exe, version: 0.9.2.0, time stamp: 0x6283b8d4
Faulting module name: unknown, version: 0.0.0.0, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x00007ff83566fca3
Faulting process id: 0x15fc
Faulting application start time: 0x01d8f4e7fa3b7194
Faulting application path: C:\Users\Mikolaj\Desktop\1\ImageEnhancingUtility.Winforms.exe
Faulting module path: unknown
Report Id: 3eb62ed2-c94c-478b-9ae8-6b2d0cf58004
Faulting package full name: 
Faulting package-relative application ID: 

Event ID: 1000
```
